### ISSUE TITLE
Kyber/NATServer

### ISSUE THREAD

**Issue by gru2007** [BattleDash/Kyber#1]
Code has references to Kyber/NATServer but this repo isn't public or maybe deleted.

Will it be public later, or need to create own SocketServer?

**Comment by BattleDash** [comment]
The NATServer is used for NAT Punch-Through, aka tricking your router into allowing UDP clients to connect by temporarily port-forwarding the game server. It is not necessary if you manually port forward 25200 in your router. I didn't include the server code here because it's very small and very easy to recreate yourself (like 10 lines of code depending on the language), but if you want to use Kyber to have people connect to your IP, port forwarding does the exact same thing.

**Comment by gru2007** [comment]
Thanks for info
