### ISSUE TITLE
Dedicated Server?

### ISSUE THREAD

**Issue by mateocabanal** [BattleDash/Kyber#10]
Currently, within the Kyber community, we do not have any permanent servers. I would love to host one, however I would need to be able to run Kyber as a dedicated server. Is it possible to implement?

**Comment by BattleDash** [comment]
The way Kyber works is by using the built-in Frostbite server in the game, which is only built to run as client+server mode. Running the game client as a dedicated server isn't feasible for many reasons, especially since you'd probably want to run it on unix. To name a few major issues there's getting the game to run under wine, Origin DRM virtualization, and removing the renderer/client when the engine isn't built in dedicated server mode,. The only non-jank and feasible way to do this is by recreating the engine's server-side from scratch, which I started doing [here](https://github.com/BattleDash/FrostbiteServer), but will probably never be finished unless some others pitch in on reversing since I don't have that much time for it now.
