### ISSUE TITLE
White screen after server start

### ISSUE THREAD

**Issue by gru2007** [BattleDash/Kyber#7]
When level loads it stucks on a white screen

[This Commit](https://github.com/BattleDash/Kyber/commit/d0588cc9c76dda50aa6b63cd4f22a8421c989917) brokes a renderer, so it doesn't working in future versions.

**Comment by BattleDash** [comment]
I've done a *lot* of testing on this. The white screen is not caused directly by that commit, but by the GUI being open while the server starts. Why this causes it I have no idea, but I've run hundreds of tests and my current solution is just forcibly closing the GUI when starting the server. The fix is in my private branch of Kyber, along with the other new features that will become available when V2 is released and no longer in my Patreon. As a temporary fix, just close the menu right after starting the server and it should work fine.

V2 will eventually have a built-in menu synonymous with the game's UI, so this shouldn't be a problem anymore. ImGui and hooking rendering systems cause much more pain and stupid issues like this than I care to deal with anymore.

**Comment by gru2007** [comment]
@BattleDash one more question, will FrostbiteServer done in near future? I tried to launch it, but there is a memory leak

**Comment by BattleDash** [comment]
> @BattleDash one more question, will FrostbiteServer done in near future? I tried to launch it, but there is a memory leak

There's no memory leak, it just loads all of the game's data at once so it's not very memory efficient. Frosty does something similar and can use tons of memory.

I can't say whether it will ever be done or not, the unfinished parts still need to be reverse engineered and I don't really have the time or motivation for it right now.
